### ISSUE TITLE
Errors. I upgraded it to latest version.

### ISSUE THREAD

**Issue by TuffLuck** [jamesoff/bmotion#32]
Hey buddy, I'm getting a bunch of errors everytime I rehash, once I restart the bot it seems to not have these errors but anytime updating info, and i rehash it breaks the bot and no longer works and I get these logs from my debug channel...

11:22:19 - Bender Debug (trace) --> can't read "bMotion_abstract_filter(_all)": no such variable while executing "set filter $bMotion_abstract_filter(_all)"
11:22:20 - Bender Debug (trace) --> can't read "bMotion_abstract_filter(_all)": no such variable while executing "set filter $bMotion_abstract_filter(_all)"
11:22:22 - Bender Debug (trace) --> can't read "bMotion_abstract_filter(_all)": no such variable while executing "set filter $bMotion_abstract_filter(_all)"
11:22:24 - Bender Debug (trace) --> can't read "bMotion_abstract_filter(_all)": no such variable while executing "set filter $bMotion_abstract_filter(_all)"
11:22:26 - Bender Debug (trace) --> can't read "bMotion_abstract_filter(_all)": no such variable while executing "set filter $bMotion_abstract_filter(_all)"
11:22:28 - Bender Debug (trace) --> can't read "bMotion_abstract_filter(_all)": no such variable while executing "set filter $bMotion_abstract_filter(_all)"
11:22:31 - Bender Debug (trace) --> can't read "needReSave": no such variable while executing "if {$needReSave} { bMotion_facts_save }" (procedure "bMotion_facts_load" line 62) invoked from within "bMotion_facts_load"
11:22:33 - Bender Debug (trace) --> couldn't read file "scripts/randomwordList.tcl": no such file or directory while executing "source "scripts/randomwordList.tcl"" (file "scripts/bmotion/modules/extra/randomword.tcl" line 3) invoked from within "source $f"
11:22:35 - Bender Debug (trace) --> couldn't read file "scripts/randomwordList.tcl": no such file or directory while executing "source "scripts/randomwordList.tcl"" (file "scripts/bmotion/modules/extra/randomword.tcl" line 3) invoked from within "source $f"
11:22:37 - Bender Debug (trace) --> can't read "bMotion_plugins_management(stats)": no such element in array while executing "set test $bMotion_plugins_management($id)"
11:22:39 - Bender Debug (trace) --> can't read "bMotionSettings(noPlugin)": no such element in array while executing "set disallowed $bMotionSettings(noPlugin)"
11:22:41 - Bender Debug (trace) --> couldn't open "scripts/bmotion/modules/stats.txt": no such file or directory while executing "open "$bMotionModules/stats.txt" "r""
11:22:43 - Bender Debug (trace) --> can't read "fileHandle": no such variable while executing "close $fileHandle"
11:22:45 - Bender Debug (trace) --> couldn't read file "scripts/bmotion/local/abstracts.tcl": no such file or directory while executing "source "$bMotionLocal/abstracts.tcl""

I have bMotion.tcl it setup like this:
Bmotion.TCL Script located:
 /home/bro/eggdrop/scripts/bMotion.tcl
Bmotion Folder located:
/home/bro/eggdrop/scripts/bmotion/

**Comment by TuffLuck** [comment]
Now, it will work on a few things but like greeting ppl on join is broke, etc also if someone highlights his name he doesnt respond etc.... and now i'm getting more output:

11:32:29 - Bender Debug (trace) --> can't read "bMotionSettings(gender)": no such element in array while executing "set val $bMotionSettings($setting)"
11:32:29 - Bender Debug (trace) --> can't read "bMotionSettings(gender)": no such element in array while executing "set val $bMotionSettings($setting)"
11:32:29 - Bender Debug (trace) --> can't read "bMotion_flood_last(xo)": no such element in array while executing "set lastCallback $bMotion_flood_last($handle)"
11:32:29 - Bender Debug (trace) --> can't read "bMotion_flood_lasttext(xo)": no such element in array while executing "set lastText $bMotion_flood_lasttext($handle)"
11:32:31 - Bender Debug (trace) --> can't read "bMotion_flood_info(xo)": no such element in array while executing "set flood $bMotion_flood_info($handle)"
11:32:33 - Bender Debug (trace) --> can't read "bMotion_flood_last(#umad)": no such element in array while executing "set lastCallback $bMotion_flood_last($handle)"
11:32:35 - Bender Debug (trace) --> can't read "bMotion_flood_lasttext(#umad)": no such element in array while executing "set lastText $bMotion_flood_lasttext($handle)"
11:32:37 - Bender Debug (trace) --> can't read "bMotion_flood_info(#umad)": no such element in array while executing "set flood $bMotion_flood_info($handle)"
11:32:39 - Bender Debug (trace) --> can't read "bMotionSettings(outputpriority)": no such element in array while executing "set val $bMotionSettings($setting)"
11:32:41 - Bender Debug (trace) --> can't read "bMotionInfo(outputpriority)": no such element in array while executing "set val $bMotionInfo($setting)"

**Comment by jamesoff** [comment]
That debug.tcl script can report things which aren't really problems, as bMotion makes heavy use of try/catch stuff, and debug.tcl reports errors even when they're handled by that.

For example (since it shows up a lot in that log you pasted), there are two main places bMotion settings live, and it works out which by trying to read it from one, and if that fails (protected in a try/catch block) it tries the other place.

That said, when trying out the script I did spot a couple of things which I can fix, but none of then are showstoppers.

Your bot's working ok now right?

**Comment by TuffLuck** [comment]
Thanks brother!
