### ISSUE TITLE
Minor bug with silence/silent variable.

### ISSUE THREAD

**Issue by voidzero** [jamesoff/bmotion#35]
Hi there. Bmotion is fantastic, I just discovered it a short while ago, what a great bot to play with. Thanks for providing it.

I found minor bug you might want to iron out, some places use `bMotionInfo(silence)` while others use `bMotionInfo(silent)`.

If I come across anything else I'll be sure to let you know. :+1: 

Do you plan on improving redis support, btw?

**Comment by jamesoff** [comment]
Thanks, I'll take a look. 

Now I know the redis integration is of use to someone else I'll go back to working on it :)

**Comment by voidzero** [comment]
Re Redis: that's great. It's been a hoot to learn more about bmotion, and redis as well. So thank you!
