### ISSUE TITLE
Mood: allow to specify negative values

### ISSUE THREAD

**Issue by voidzero** [jamesoff/bmotion#36]
Small patch so users can set e.g. `.bmotion mood set lonely -30`. Values < -30 and > 30 are adjusted.
[bmotion_mood.txt](https://github.com/jamesoff/bmotion/files/129454/bmotion_mood.txt)

**Comment by GLolol** [comment]
You can send patches as a pull request: fork the repository, apply the patch in your fork, push changes, and [create a pull request](https://github.com/jamesoff/bmotion/compare).
