### ISSUE TITLE
Tcl error [bMotion_event_action]: can't read "mood(horny)": no such variable

### ISSUE THREAD

**Issue by rvzm** [jamesoff/bmotion#37]
whenever I do /me gives <botnick> a dildo, it reports in the partyline this:
[06:49:37] Tcl error [bMotion_event_action]: can't read "mood(horny)": no such variable

I searched the settings file, but found nothing for that setting. any ideas?

**Comment by jamesoff** [comment]
Filed under: bug reports you never imagined you'd write.

This looks like that plugin is using the old method of tracking moods rather than the new one.

**Comment by rvzm** [comment]
alright. trying a update to the files and seeing if that fixes it

**Comment by jamesoff** [comment]
I can reproduce it, so it's bad code rather than you being out of date :)

**Comment by rvzm** [comment]
oh
