### ISSUE TITLE
possibility to set the bmotion path manually in eggdrop.conf or similar

### ISSUE THREAD

**Issue by lilmike** [jamesoff/bmotion#38]
Hi,
I have an odd setup, where the eggdrop's plugin path is /usr/share/eggdrop/plugins or something, as I got it from a package. However, bmotion doesn't seem to know where to find the bmotion path when I don't run from that directory (which I obviously don't want to do). Any way there can be an override in eggdrop.conf or similar for the bmotion path?
Thanks,
-Michael.

**Comment by jamesoff** [comment]
Maybe a thing where you're you can set the bmotion root before souring the script and it can honour that instead of using the default?

**Comment by jamesoff** [comment]
This was done in 224df9e0
