### ISSUE TITLE
Error message in bots

### ISSUE THREAD

**Issue by aflove65** [jamesoff/bmotion#40]
[09:02:49] Tcl error [bMotion_interbot_catch]: can't read "function": no such variable

I get this in the bots when bmotion is running. Any ideas?

**Comment by jamesoff** [comment]
Do you have other bots linked on the botnet? Are they running bMotion too? Are the bots in the same channels together? (Is this only happening on one bot?) Are they running the same version of bMotion? Which version of TCL is your bot using?

Can you reproduce it on demand?

If you don't mind seeing a lot of output, can you do `.console +d12` on the partyline? It'll generate quite a bit of debug output from bMotion, but hopefully shortly before the error will be some information about what happened to cause it. Looking at the code, that might fail too, in which case, do `.console +d123`. That generates more output, but will log what the bot got on the botnet before any processing takes place; the line you're looking for will go `interbot: incoming !...!` with some text between the `!`s.

**Comment by aflove65** [comment]
I updated the interbot.tcl with the newer version and that seems to have fixed it.
