### ISSUE TITLE
can't read "reason": no such variable

### ISSUE THREAD

**Issue by roughnecks** [jamesoff/bmotion#44]
Hello,
not sure if this can be described as a bug but whenever someone parts from channel (I believe without an actual message), the bot spits this out on the party line:

> Tcl error [bMotion_event_onpart]: can't read "reason": no such variable

**Comment by roughnecks** [comment]
Thanks

**Comment by jamesoff** [comment]
Let me know if that doesn't fix it, and thanks for the report :)
