### ISSUE TITLE
Remote host closed the connection

### ISSUE THREAD

**Issue by roughnecks** [jamesoff/bmotion#45]
Hello,

I'm still not sure if this is entirely related to bMotion.. I'm currently testing with the script disabled.

I have an eggdrop on libera. Initially it was inside one channel only, bMotion enabled and all was fine. Then I made it join a second channel and I enabled bMotion there too.. This is when issues started happening with the bot shutting down with the message in subject, without any apparent motivation.

Then I looked at timestamps and DCC CHAT with the bot and it looks like bMotion might be the culprit.. Whenever it's autosaving facts or doing self-diagnostics, the bot shuts down and so my DCC also quits.

I have disabled bMotion on all channels - via the .chanset #channel -bmotion setting - like 10 minutes ago and I just received this message in partyline:

`[12:18:00] bMotion: All channels are idle, going away`

Honestly I'm quite lost here, any advice is appreciated. Thanks

**Comment by roughnecks** [comment]
Nevermind, I found the issue.

That problematic channel has a relay set to a Telegram private group and whenever someone posts an emoticon my bot quits.
It probably has to do with how tcl is compiled on the shell I'm running the eggrop on.

Sorry for the mess :(

**Comment by jamesoff** [comment]
Hey, no worries about the issue :)

This sounds like something I looked at before and fixed in bMotion, and also have a workaround for. Check #43 for the details.
